export const SET_TYPE_PAGE = 'parent/SET_TYPE_PAGE';
export const SET_REQUEST_PAGE = 'parent/SET_REQUEST_PAGE';

// movie Action
export const FETCH_DATA_LIST_MOVIE = 'movie/FETCH_DATA_LIST_MOVIE';
export const SHOW_MODAL_VIDEO = 'movie/SHOW_MODAL_VIDEO';
export const HIRE_MODAL_VIDEO = 'movie/HIRE_MODAL_VIDEO';
export const FETCH_DATA_MOVIEINFO_WITH_MOVIEID = 'movie/FETCH_DATA_MOVIEINFO_WITH_MOVIEID';
export const SET_DATA_lIST_LICH_CHIEU = 'movie/SET_DATA_lIST_LICH_CHIEU';
export const FIND_THEATER_SYSTEM_WITH_DATE = 'movie/FIND_THEATER_SYSTEM_WITH_DATE';
export const SET_DATA_LIST_PHONGVE_MALICHCHIEU = 'movie/SET_DATA_LIST_PHONGVE_MALICHCHIEU';
export const SET_IS_ACTVED_GHE_ITEM = 'movie/SET_IS_ACTVED_GHE_ITEM';
export const SET_DATA_AMOUNT_GHE = 'movie/SET_DATA_AMOUNT_GHE';
export const SET_DATA_LIST_MOVIE_PHAN_TRANG = 'movie/SET_DATA_LIST_MOVIE_PHAN_TRANG';
// theaterSystem action
export const FETCH_DATA_LIST_THEARTERSYSTEM = 'theatersystem/FETCH_DATA_LIST_THEARTERSYSTEM';
export const FETCH_DATA_LIST_THEARTER_WITH_ID_THEARTERSYSTEM = 'theatersystem/FETCH_DATA_LIST_THEARTER_WITH_ID_THEARTERSYSTEM';
export const FETCH_DATA_THEATERSYSEM_INFO_WITH_ID_THEARTERSYSTEM = 'theatersystem/FETCH_DATA_THEATERSYSEM_INFO_WITH_ID_THEARTERSYSTEM';
export const SET_DATA_LIST_MOVIE_WITH_THEATER = 'theatersystem/SET_DATA_LIST_MOVIE_WITH_THEATER';



